//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branches()
        {
            this.BranchStaff = new HashSet<BranchStaff>();
        }
    
        public int id { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> DataOtkretia { get; set; }
        public Nullable<int> idStaff { get; set; }
        public string Name { get; set; }
        public Nullable<double> ColichestvoSotrudnikov { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchStaff> BranchStaff { get; set; }
    }
}
