//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchStaff
    {
        public int id { get; set; }
        public Nullable<int> idStaff { get; set; }
        public Nullable<int> idBranches { get; set; }
    
        public virtual Branches Branches { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
