//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policies
    {
        public int id { get; set; }
        public string InsuranceType { get; set; }
        public Nullable<double> InsurancePremium { get; set; }
        public Nullable<double> InsuranceAmount { get; set; }
        public Nullable<System.DateTime> DateOfConclusion { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> idClienta { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
