//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyHolder
    {
        public int id { get; set; }
        public string Familia { get; set; }
        public string Name { get; set; }
        public string Otchestvo { get; set; }
        public Nullable<double> SeriesPassport { get; set; }
        public Nullable<double> NomerPassporta { get; set; }
        public Nullable<double> Telephone { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
    }
}
