//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realty
    {
        public int id { get; set; }
        public string Adress { get; set; }
        public Nullable<double> Ploshad { get; set; }
        public string FIOSobstvenika { get; set; }
        public string PassportNedvijimosti { get; set; }
        public Nullable<System.DateTime> DataRegistracii { get; set; }
        public Nullable<int> idContract { get; set; }
        public Nullable<int> typ { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual typerealty typerealty { get; set; }
    }
}
